version: "3.7"

services:
  app:
    container_name: app
    build: .
    ports:
      - 3333:3333
    networks:
      - network
    env_file:
      - .env
    volumes:
      - app:/usr/src/app/data

  bibliotec-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSSWORD: bibliotec
      MYSQL_DATABASE: bibliotec
      MYSQL_USER: root
      MYSQL_PASSWORD:
    container_name: bibliotec-db
    networks:
      - network

volumes:
  mysql:
    name: bibliotec-db
  app:
    name: bibliotec-app

networks:
  network:
    name: bibliotec-network
